# Generated by Django 3.1.2 on 2021-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.TextField(default='undefined', verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.TextField(default='undefined', verbose_name='Color'),
            preserve_default=False,
        ),
    ]
