# Generated by Django 3.1.2 on 2021-01-18 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210118_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='AvgRating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.TextField(verbose_name='CurrentPrice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.TextField(verbose_name='OldPrice'),
        ),
    ]
