# Generated by Django 3.1.2 on 2021-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(default='Undefined', verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(default='Undefined', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
