# Generated by Django 3.1.2 on 2021-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.FloatField(verbose_name='CurrentPrice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(verbose_name='OldPrice'),
        ),
    ]
